steps:
  install:
    image: danlynn/ember-cli:5.12.0-node_22.9
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:5.12.0-node_22.9
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:5.12.0-node_22.9
    group: lint
    commands:
      - npm run lint:hbs
  lint-css:
    image: danlynn/ember-cli:5.12.0-node_22.9
    group: lint
    commands:
      - npm run lint:css
  dependency-lint:
    image: danlynn/ember-cli:5.12.0-node_22.9
    group: lint
    commands:
      - npm run lint:dependencies
  test:
    image: danlynn/ember-cli:5.12.0-node_22.9
    commands:
      - npm run test:ember
when:
  - event: pull_request
