steps:
  install:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm install
  lint-js:
    image: danlynn/ember-cli:5.8.0-node_20.12
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:5.8.0-node_20.12
    group: lint
    commands:
      - npm run lint:hbs
  lint-css:
    image: danlynn/ember-cli:5.8.0-node_20.12
    group: lint
    commands:
      - npm run lint:css
  # TODO: set up dependency lint
  # dependency-lint:
  #   image: danlynn/ember-cli:5.8.0-node_20.12
  #   group: lint
  #   commands:
  #     - ember dependency-lint
  test:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm run test:ember
when:
  event: pull_request
